package com.shifuu.diabeticsdiary.loginactivity.registration;

import android.app.Application;

import com.shifuu.diabeticsdiary.database.AppRepository;
import com.shifuu.diabeticsdiary.database.food.FoodEntity;

import java.text.DecimalFormat;

public class DefaultDatabaseInserter {
    AppRepository appRepository;
    DefaultDatabaseInserter(Application application)
    {
        appRepository = new AppRepository(application);
    }

    public void insert(long uid)
    {
        appRepository.insertFood(new FoodEntity(0, "", "Ацидофилин 1%", 40, "100г", uid, (int)Math.round(4), (int)Math.round(3), (int)Math.round(1)));
        appRepository.insertFood(new FoodEntity(0, "", "Ацидофилин 3,2%", 59, "100г", uid, (int)Math.round(3.8), (int)Math.round(2.9), (int)Math.round(3.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Ацидофилин 3,2% сладкий", 77, "100г", uid, (int)Math.round(8.6), (int)Math.round(2.8), (int)Math.round(3.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Ацидофилин нежирный", 31, "100г", uid, (int)Math.round(3.9), (int)Math.round(3), (int)Math.round(0.05)));
        appRepository.insertFood(new FoodEntity(0, "", "Брынза (из коровьего молока)", 262, "100г", uid, (int)Math.round(0.4), (int)Math.round(22.1), (int)Math.round(19.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Варенец 2,5%", 53, "100г", uid, (int)Math.round(4.1), (int)Math.round(2.9), (int)Math.round(2.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Запеканка из обезжиренного творога", 168, "100г", uid, (int)Math.round(14.2), (int)Math.round(17.6), (int)Math.round(4.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Йогурт 1,5%", 57, "100г", uid, (int)Math.round(5.9), (int)Math.round(4.1), (int)Math.round(1.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Йогурт 1,5% плодово-ягодный", 90, "100г", uid, (int)Math.round(14.3), (int)Math.round(4), (int)Math.round(1.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Йогурт 3,2%", 68, "100г", uid, (int)Math.round(3.5), (int)Math.round(5), (int)Math.round(3.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Йогурт 3,2% сладкий", 87, "100г", uid, (int)Math.round(8.5), (int)Math.round(5), (int)Math.round(3.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Йогурт 6%", 92, "100г", uid, (int)Math.round(3.5), (int)Math.round(5), (int)Math.round(6)));
        appRepository.insertFood(new FoodEntity(0, "", "Йогурт 6% сладкий", 112, "100г", uid, (int)Math.round(8.5), (int)Math.round(5), (int)Math.round(6)));
        appRepository.insertFood(new FoodEntity(0, "", "Кефир 1%", 40, "100г", uid, (int)Math.round(4), (int)Math.round(3), (int)Math.round(1)));
        appRepository.insertFood(new FoodEntity(0, "", "Кефир 2,5%", 53, "100г", uid, (int)Math.round(4), (int)Math.round(2.9), (int)Math.round(2.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Кефир 3,2%", 59, "100г", uid, (int)Math.round(4), (int)Math.round(2.9), (int)Math.round(3.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Кефир нежирный", 31, "100г", uid, (int)Math.round(4), (int)Math.round(3), (int)Math.round(0.05)));
        appRepository.insertFood(new FoodEntity(0, "", "Кумыс (из кобыльего молока)", 50, "100г", uid, (int)Math.round(5), (int)Math.round(2.1), (int)Math.round(1.9)));
        appRepository.insertFood(new FoodEntity(0, "", "Кумыс нежирный (из коровьего молока)", 41, "100г", uid, (int)Math.round(6.3), (int)Math.round(3), (int)Math.round(0.05)));
        appRepository.insertFood(new FoodEntity(0, "", "Масса творожная 16,5% жирности", 232, "100г", uid, (int)Math.round(9.5), (int)Math.round(12), (int)Math.round(16.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Молоко 1,5%", 45, "100г", uid, (int)Math.round(4.8), (int)Math.round(3), (int)Math.round(1.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Молоко 2,5%", 54, "100г", uid, (int)Math.round(4.8), (int)Math.round(2.9), (int)Math.round(2.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Молоко 3,2%", 60, "100г", uid, (int)Math.round(4.7), (int)Math.round(2.9), (int)Math.round(3.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Молоко 3,5%", 62, "100г", uid, (int)Math.round(4.7), (int)Math.round(2.9), (int)Math.round(3.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Молоко козье", 69, "100г", uid, (int)Math.round(4.5), (int)Math.round(3.6), (int)Math.round(4.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Молоко нежирное", 32, "100г", uid, (int)Math.round(4.9), (int)Math.round(3), (int)Math.round(0.05)));
        appRepository.insertFood(new FoodEntity(0, "", "Молоко сгущённое с сахаром 5%", 295, "100г", uid, (int)Math.round(55.2), (int)Math.round(7.1), (int)Math.round(5)));
        appRepository.insertFood(new FoodEntity(0, "", "Молоко сгущённое с сахаром 8,5%", 328, "100г", uid, (int)Math.round(55.5), (int)Math.round(7.2), (int)Math.round(8.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Молоко сгущённое с сахаром нежирное", 259, "100г", uid, (int)Math.round(56.8), (int)Math.round(7.5), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Молоко сухое 15%", 432, "100г", uid, (int)Math.round(44.7), (int)Math.round(28.5), (int)Math.round(15)));
        appRepository.insertFood(new FoodEntity(0, "", "Молоко сухое 25%", 483, "100г", uid, (int)Math.round(39.3), (int)Math.round(24.2), (int)Math.round(25)));
        appRepository.insertFood(new FoodEntity(0, "", "Молоко сухое нежирное", 362, "100г", uid, (int)Math.round(52.6), (int)Math.round(33.2), (int)Math.round(1)));
        appRepository.insertFood(new FoodEntity(0, "", "Мороженое пломбир", 232, "100г", uid, (int)Math.round(20.4), (int)Math.round(3.7), (int)Math.round(15)));
        appRepository.insertFood(new FoodEntity(0, "", "Мороженое сливочное", 183, "100г", uid, (int)Math.round(19.4), (int)Math.round(3.3), (int)Math.round(10)));
        appRepository.insertFood(new FoodEntity(0, "", "Пахта", 41, "100г", uid, (int)Math.round(4.7), (int)Math.round(3.3), (int)Math.round(1)));
        appRepository.insertFood(new FoodEntity(0, "", "Простокваша 1%", 40, "100г", uid, (int)Math.round(4.1), (int)Math.round(3), (int)Math.round(1)));
        appRepository.insertFood(new FoodEntity(0, "", "Простокваша 2,5%", 53, "100г", uid, (int)Math.round(4.1), (int)Math.round(2.9), (int)Math.round(2.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Простокваша 3,2%", 59, "100г", uid, (int)Math.round(4.1), (int)Math.round(2.9), (int)Math.round(3.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Простокваша нежирная", 30, "100г", uid, (int)Math.round(3.8), (int)Math.round(3), (int)Math.round(0.05)));
        appRepository.insertFood(new FoodEntity(0, "", "Ряженка 1%", 40, "100г", uid, (int)Math.round(4.2), (int)Math.round(3), (int)Math.round(1)));
        appRepository.insertFood(new FoodEntity(0, "", "Ряженка 2,5%", 54, "100г", uid, (int)Math.round(4.2), (int)Math.round(2.9), (int)Math.round(2.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Ряженка 4%", 67, "100г", uid, (int)Math.round(4.2), (int)Math.round(2.8), (int)Math.round(4)));
        appRepository.insertFood(new FoodEntity(0, "", "Ряженка 6%", 85, "100г", uid, (int)Math.round(4.1), (int)Math.round(3), (int)Math.round(6)));
        appRepository.insertFood(new FoodEntity(0, "", "Сливки 10%", 119, "100г", uid, (int)Math.round(4.5), (int)Math.round(2.7), (int)Math.round(10)));
        appRepository.insertFood(new FoodEntity(0, "", "Сливки 20%", 207, "100г", uid, (int)Math.round(4), (int)Math.round(2.5), (int)Math.round(20)));
        appRepository.insertFood(new FoodEntity(0, "", "Сливки 25%", 251, "100г", uid, (int)Math.round(3.9), (int)Math.round(2.4), (int)Math.round(25)));
        appRepository.insertFood(new FoodEntity(0, "", "Сливки 35%", 337, "100г", uid, (int)Math.round(3.2), (int)Math.round(2.2), (int)Math.round(35)));
        appRepository.insertFood(new FoodEntity(0, "", "Сливки 8%", 102, "100г", uid, (int)Math.round(4.5), (int)Math.round(2.8), (int)Math.round(8)));
        appRepository.insertFood(new FoodEntity(0, "", "Сливки сгущённые с сахаром 19%", 392, "100г", uid, (int)Math.round(47), (int)Math.round(8), (int)Math.round(19)));
        appRepository.insertFood(new FoodEntity(0, "", "Сливки сухие 42%", 577, "100г", uid, (int)Math.round(30.2), (int)Math.round(19), (int)Math.round(42)));
        appRepository.insertFood(new FoodEntity(0, "", "Сметана 10%", 119, "100г", uid, (int)Math.round(3.9), (int)Math.round(2.7), (int)Math.round(10)));
        appRepository.insertFood(new FoodEntity(0, "", "Сметана 15%", 162, "100г", uid, (int)Math.round(3.6), (int)Math.round(2.6), (int)Math.round(15)));
        appRepository.insertFood(new FoodEntity(0, "", "Сметана 20%", 206, "100г", uid, (int)Math.round(3.4), (int)Math.round(2.5), (int)Math.round(20)));
        appRepository.insertFood(new FoodEntity(0, "", "Сметана 25%", 250, "100г", uid, (int)Math.round(3.2), (int)Math.round(2.4), (int)Math.round(25)));
        appRepository.insertFood(new FoodEntity(0, "", "Сметана 30%", 293, "100г", uid, (int)Math.round(3.1), (int)Math.round(2.3), (int)Math.round(30)));
        appRepository.insertFood(new FoodEntity(0, "", "Сыр Адыгейский", 264, "100г", uid, (int)Math.round(1.5), (int)Math.round(19.8), (int)Math.round(19.8)));
        appRepository.insertFood(new FoodEntity(0, "", "Сыр Голландский 45%", 350, "100г", uid, (int)Math.round(0), (int)Math.round(26.3), (int)Math.round(26.6)));
        appRepository.insertFood(new FoodEntity(0, "", "Сыр Камамбер", 324, "100г", uid, (int)Math.round(0.1), (int)Math.round(15.3), (int)Math.round(28.8)));
        appRepository.insertFood(new FoodEntity(0, "", "Сыр Пармезан", 392, "100г", uid, (int)Math.round(0.8), (int)Math.round(35.7), (int)Math.round(25.8)));
        appRepository.insertFood(new FoodEntity(0, "", "Сыр Пошехонский 45%", 344, "100г", uid, (int)Math.round(0), (int)Math.round(26), (int)Math.round(26.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Сыр Рокфор 50%", 335, "100г", uid, (int)Math.round(0), (int)Math.round(20.5), (int)Math.round(27.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Сыр Российский 50%", 364, "100г", uid, (int)Math.round(0), (int)Math.round(23.2), (int)Math.round(29.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Сыр Сулугуни", 286, "100г", uid, (int)Math.round(0.4), (int)Math.round(20.5), (int)Math.round(22)));
        appRepository.insertFood(new FoodEntity(0, "", "Сыр Фета", 264, "100г", uid, (int)Math.round(4.1), (int)Math.round(14.2), (int)Math.round(21.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Сыр Чеддер 50%", 380, "100г", uid, (int)Math.round(0), (int)Math.round(23.5), (int)Math.round(30.8)));
        appRepository.insertFood(new FoodEntity(0, "", "Сыр Швейцарский 50%", 391, "100г", uid, (int)Math.round(0), (int)Math.round(24.6), (int)Math.round(31.6)));
        appRepository.insertFood(new FoodEntity(0, "", "Сыр Гауда", 356, "100г", uid, (int)Math.round(2.2), (int)Math.round(24.9), (int)Math.round(27.4)));
        appRepository.insertFood(new FoodEntity(0, "", "Сыр нежирный", 86, "100г", uid, (int)Math.round(1.5), (int)Math.round(18), (int)Math.round(0.6)));
        appRepository.insertFood(new FoodEntity(0, "", "Сыр плавленый Колбасный", 275, "100г", uid, (int)Math.round(3.7), (int)Math.round(21.2), (int)Math.round(19.4)));
        appRepository.insertFood(new FoodEntity(0, "", "Сыр плавленый Российский", 300, "100г", uid, (int)Math.round(2.5), (int)Math.round(20.5), (int)Math.round(23)));
        appRepository.insertFood(new FoodEntity(0, "", "Сырки глазированные 27,7% жирности", 413, "100г", uid, (int)Math.round(32.6), (int)Math.round(7.9), (int)Math.round(27.7)));
        appRepository.insertFood(new FoodEntity(0, "", "Сырники из обезжиренного творога", 183, "100г", uid, (int)Math.round(18.2), (int)Math.round(18.6), (int)Math.round(3.6)));
        appRepository.insertFood(new FoodEntity(0, "", "Творог 11%", 178, "100г", uid, (int)Math.round(3), (int)Math.round(16), (int)Math.round(11)));
        appRepository.insertFood(new FoodEntity(0, "", "Творог 18% (жирный)", 236, "100г", uid, (int)Math.round(2.8), (int)Math.round(15), (int)Math.round(18)));
        appRepository.insertFood(new FoodEntity(0, "", "Творог 2%", 114, "100г", uid, (int)Math.round(3), (int)Math.round(20), (int)Math.round(2)));
        appRepository.insertFood(new FoodEntity(0, "", "Творог 4%", 136, "100г", uid, (int)Math.round(3), (int)Math.round(21), (int)Math.round(4)));
        appRepository.insertFood(new FoodEntity(0, "", "Творог 5%", 145, "100г", uid, (int)Math.round(3), (int)Math.round(21), (int)Math.round(5)));
        appRepository.insertFood(new FoodEntity(0, "", "Творог 9% (полужирный)", 169, "100г", uid, (int)Math.round(3), (int)Math.round(18), (int)Math.round(9)));
        appRepository.insertFood(new FoodEntity(0, "", "Творог нежирный", 110, "100г", uid, (int)Math.round(3.3), (int)Math.round(22), (int)Math.round(0.6)));
        appRepository.insertFood(new FoodEntity(0, "", "Белок куриного яйца", 48, "100г", uid, (int)Math.round(1), (int)Math.round(11.1), (int)Math.round(0)));
        appRepository.insertFood(new FoodEntity(0, "", "Желток куриного яйца", 354, "100г", uid, (int)Math.round(0), (int)Math.round(16.2), (int)Math.round(31.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Яичный порошок", 542, "100г", uid, (int)Math.round(4.5), (int)Math.round(46), (int)Math.round(37.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Яйцо куриное", 157, "100г", uid, (int)Math.round(0.7), (int)Math.round(12.7), (int)Math.round(11.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Яйцо перепелиное", 168, "100г", uid, (int)Math.round(0.6), (int)Math.round(11.9), (int)Math.round(13.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Вобла", 95, "100г", uid, (int)Math.round(0), (int)Math.round(18), (int)Math.round(2.8)));
        appRepository.insertFood(new FoodEntity(0, "", "Горбуша", 140, "100г", uid, (int)Math.round(0), (int)Math.round(20.5), (int)Math.round(6.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Горбуша натуральная (консервы)", 136, "100г", uid, (int)Math.round(0), (int)Math.round(20.9), (int)Math.round(5.8)));
        appRepository.insertFood(new FoodEntity(0, "", "Икра красная зернистая", 249, "100г", uid, (int)Math.round(1), (int)Math.round(31.5), (int)Math.round(13.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Икра минтая", 132, "100г", uid, (int)Math.round(1.1), (int)Math.round(27.9), (int)Math.round(1.8)));
        appRepository.insertFood(new FoodEntity(0, "", "Икра чёрная зернистая", 235, "100г", uid, (int)Math.round(0.8), (int)Math.round(26.8), (int)Math.round(13.8)));
        appRepository.insertFood(new FoodEntity(0, "", "Кальмар", 100, "100г", uid, (int)Math.round(2), (int)Math.round(18), (int)Math.round(2.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Камбала", 90, "100г", uid, (int)Math.round(0), (int)Math.round(15.7), (int)Math.round(3)));
        appRepository.insertFood(new FoodEntity(0, "", "Кета", 127, "100г", uid, (int)Math.round(0), (int)Math.round(19), (int)Math.round(5.6)));
        appRepository.insertFood(new FoodEntity(0, "", "Килька балтийская", 137, "100г", uid, (int)Math.round(0), (int)Math.round(14.1), (int)Math.round(9)));
        appRepository.insertFood(new FoodEntity(0, "", "Килька каспийская", 192, "100г", uid, (int)Math.round(0), (int)Math.round(18.5), (int)Math.round(13.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Креветка", 98, "100г", uid, (int)Math.round(0.3), (int)Math.round(20.5), (int)Math.round(1.6)));
        appRepository.insertFood(new FoodEntity(0, "", "Лещ", 105, "100г", uid, (int)Math.round(0), (int)Math.round(17.1), (int)Math.round(4.4)));
        appRepository.insertFood(new FoodEntity(0, "", "Лосось атлантический (сёмга)", 153, "100г", uid, (int)Math.round(0), (int)Math.round(20), (int)Math.round(8.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Мидии", 77, "100г", uid, (int)Math.round(3.3), (int)Math.round(11.5), (int)Math.round(2)));
        appRepository.insertFood(new FoodEntity(0, "", "Минтай", 72, "100г", uid, (int)Math.round(0), (int)Math.round(15.9), (int)Math.round(0.9)));
        appRepository.insertFood(new FoodEntity(0, "", "Мойва", 166, "100г", uid, (int)Math.round(0), (int)Math.round(13.4), (int)Math.round(12.6)));
        appRepository.insertFood(new FoodEntity(0, "", "Навага", 91, "100г", uid, (int)Math.round(0), (int)Math.round(19.2), (int)Math.round(1.6)));
        appRepository.insertFood(new FoodEntity(0, "", "Окунь морской", 103, "100г", uid, (int)Math.round(0), (int)Math.round(18.2), (int)Math.round(3.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Окунь речной", 82, "100г", uid, (int)Math.round(0), (int)Math.round(18.5), (int)Math.round(0.9)));
        appRepository.insertFood(new FoodEntity(0, "", "Осётр", 164, "100г", uid, (int)Math.round(0), (int)Math.round(16.4), (int)Math.round(10.9)));
        appRepository.insertFood(new FoodEntity(0, "", "Палтус", 103, "100г", uid, (int)Math.round(0), (int)Math.round(18.9), (int)Math.round(3)));
        appRepository.insertFood(new FoodEntity(0, "", "Печень трески (консервы)", 613, "100г", uid, (int)Math.round(1.2), (int)Math.round(4.2), (int)Math.round(65.7)));
        appRepository.insertFood(new FoodEntity(0, "", "Пикша", 73, "100г", uid, (int)Math.round(0), (int)Math.round(17.2), (int)Math.round(0.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Рак речной", 76, "100г", uid, (int)Math.round(1.2), (int)Math.round(15.5), (int)Math.round(1)));
        appRepository.insertFood(new FoodEntity(0, "", "Рыбий жир (из печени трески)", 898, "100г", uid, (int)Math.round(0), (int)Math.round(0), (int)Math.round(99.8)));
        appRepository.insertFood(new FoodEntity(0, "", "Сазан", 97, "100г", uid, (int)Math.round(0), (int)Math.round(18.2), (int)Math.round(2.7)));
        appRepository.insertFood(new FoodEntity(0, "", "Салака", 125, "100г", uid, (int)Math.round(0), (int)Math.round(17), (int)Math.round(6.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Сельдь жирная", 248, "100г", uid, (int)Math.round(0), (int)Math.round(17.7), (int)Math.round(19.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Сельдь нежирная", 135, "100г", uid, (int)Math.round(0), (int)Math.round(19.1), (int)Math.round(6.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Сельдь среднесолёная", 145, "100г", uid, (int)Math.round(0), (int)Math.round(17), (int)Math.round(8.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Скумбрия", 191, "100г", uid, (int)Math.round(0), (int)Math.round(18), (int)Math.round(13.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Скумбрия в масле (консервы)", 318, "100г", uid, (int)Math.round(0), (int)Math.round(14.4), (int)Math.round(28.9)));
        appRepository.insertFood(new FoodEntity(0, "", "Сом", 115, "100г", uid, (int)Math.round(0), (int)Math.round(17.2), (int)Math.round(5.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Ставрида", 114, "100г", uid, (int)Math.round(0), (int)Math.round(18.5), (int)Math.round(4.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Судак", 84, "100г", uid, (int)Math.round(0), (int)Math.round(18.4), (int)Math.round(1.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Треска", 69, "100г", uid, (int)Math.round(0), (int)Math.round(16), (int)Math.round(0.6)));
        appRepository.insertFood(new FoodEntity(0, "", "Тунец", 139, "100г", uid, (int)Math.round(0), (int)Math.round(24.4), (int)Math.round(4.6)));
        appRepository.insertFood(new FoodEntity(0, "", "Угорь", 333, "100г", uid, (int)Math.round(0), (int)Math.round(14.5), (int)Math.round(30.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Устрица", 72, "100г", uid, (int)Math.round(4.5), (int)Math.round(9), (int)Math.round(2)));
        appRepository.insertFood(new FoodEntity(0, "", "Хек", 86, "100г", uid, (int)Math.round(0), (int)Math.round(16.6), (int)Math.round(2.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Шпроты в масле (консервы)", 363, "100г", uid, (int)Math.round(0), (int)Math.round(17.4), (int)Math.round(32.4)));
        appRepository.insertFood(new FoodEntity(0, "", "Щука", 84, "100г", uid, (int)Math.round(0), (int)Math.round(18.4), (int)Math.round(1.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Батон нарезной", 262, "100г", uid, (int)Math.round(51.4), (int)Math.round(7.5), (int)Math.round(2.9)));
        appRepository.insertFood(new FoodEntity(0, "", "Гречиха (зерно)", 296, "100г", uid, (int)Math.round(56), (int)Math.round(10.8), (int)Math.round(3.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Каша гречневая (из крупы ядрица)", 101, "100г", uid, (int)Math.round(14.6), (int)Math.round(4), (int)Math.round(1.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Каша из овсяных хлопьев Геркулес", 105, "100г", uid, (int)Math.round(14.8), (int)Math.round(2.4), (int)Math.round(4)));
        appRepository.insertFood(new FoodEntity(0, "", "Каша манная", 100, "100г", uid, (int)Math.round(16.4), (int)Math.round(2.2), (int)Math.round(2.9)));
        appRepository.insertFood(new FoodEntity(0, "", "Каша овсяная", 109, "100г", uid, (int)Math.round(15.5), (int)Math.round(2.6), (int)Math.round(4.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Каша перловая", 135, "100г", uid, (int)Math.round(22.9), (int)Math.round(2.9), (int)Math.round(3.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Каша пшеничная", 153, "100г", uid, (int)Math.round(25.7), (int)Math.round(4.4), (int)Math.round(3.6)));
        appRepository.insertFood(new FoodEntity(0, "", "Каша пшенная", 109, "100г", uid, (int)Math.round(16.8), (int)Math.round(2.8), (int)Math.round(3.4)));
        appRepository.insertFood(new FoodEntity(0, "", "Каша рисовая", 144, "100г", uid, (int)Math.round(25.8), (int)Math.round(2.4), (int)Math.round(3.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Крупа гречневая (продел)", 300, "100г", uid, (int)Math.round(60.4), (int)Math.round(9.5), (int)Math.round(2.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Крупа гречневая (ядрица)", 308, "100г", uid, (int)Math.round(57.1), (int)Math.round(12.6), (int)Math.round(3.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Крупа кукурузная", 328, "100г", uid, (int)Math.round(71), (int)Math.round(8.3), (int)Math.round(1.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Крупа манная", 333, "100г", uid, (int)Math.round(70.6), (int)Math.round(10.3), (int)Math.round(1)));
        appRepository.insertFood(new FoodEntity(0, "", "Крупа овсяная", 342, "100г", uid, (int)Math.round(59.5), (int)Math.round(12.3), (int)Math.round(6.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Крупа перловая", 315, "100г", uid, (int)Math.round(66.9), (int)Math.round(9.3), (int)Math.round(1.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Крупа пшеничная", 329, "100г", uid, (int)Math.round(68.5), (int)Math.round(11), (int)Math.round(1.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Крупа пшено (шлифованное)", 342, "100г", uid, (int)Math.round(66.5), (int)Math.round(11.5), (int)Math.round(3.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Крупа рисовая", 333, "100г", uid, (int)Math.round(74), (int)Math.round(7), (int)Math.round(1)));
        appRepository.insertFood(new FoodEntity(0, "", "Крупа ячневая", 313, "100г", uid, (int)Math.round(65.4), (int)Math.round(10), (int)Math.round(1.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Кукуруза консервированная", 58, "100г", uid, (int)Math.round(11.2), (int)Math.round(2.2), (int)Math.round(0.4)));
        appRepository.insertFood(new FoodEntity(0, "", "Кукуруза сладкая", 86, "100г", uid, (int)Math.round(19), (int)Math.round(3.2), (int)Math.round(1.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Макароны из муки 1 сорта", 333, "100г", uid, (int)Math.round(68.4), (int)Math.round(11.2), (int)Math.round(1.6)));
        appRepository.insertFood(new FoodEntity(0, "", "Макароны из муки в/с", 338, "100г", uid, (int)Math.round(70.5), (int)Math.round(11), (int)Math.round(1.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Макароны отварные", 98, "100г", uid, (int)Math.round(20), (int)Math.round(3.6), (int)Math.round(0.4)));
        appRepository.insertFood(new FoodEntity(0, "", "Мука гречневая", 335, "100г", uid, (int)Math.round(70.6), (int)Math.round(12.6), (int)Math.round(3.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Мука кукурузная", 331, "100г", uid, (int)Math.round(72.1), (int)Math.round(7.2), (int)Math.round(1.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Мука овсяная", 369, "100г", uid, (int)Math.round(64.9), (int)Math.round(13), (int)Math.round(6.8)));
        appRepository.insertFood(new FoodEntity(0, "", "Мука овсяная (толокно)", 363, "100г", uid, (int)Math.round(64.9), (int)Math.round(12.5), (int)Math.round(6)));
        appRepository.insertFood(new FoodEntity(0, "", "Мука пшеничная 1 сорта", 329, "100г", uid, (int)Math.round(67.8), (int)Math.round(11.1), (int)Math.round(1.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Мука пшеничная 2 сорта", 322, "100г", uid, (int)Math.round(64.8), (int)Math.round(11.6), (int)Math.round(1.8)));
        appRepository.insertFood(new FoodEntity(0, "", "Мука пшеничная в/с", 334, "100г", uid, (int)Math.round(69.9), (int)Math.round(10.8), (int)Math.round(1.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Мука пшеничная обойная", 312, "100г", uid, (int)Math.round(61.5), (int)Math.round(11.5), (int)Math.round(2.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Мука ржаная обдирная", 298, "100г", uid, (int)Math.round(61.8), (int)Math.round(8.9), (int)Math.round(1.7)));
        appRepository.insertFood(new FoodEntity(0, "", "Мука ржаная обойная", 294, "100г", uid, (int)Math.round(58.5), (int)Math.round(10.7), (int)Math.round(1.9)));
        appRepository.insertFood(new FoodEntity(0, "", "Мука ржаная сеяная", 305, "100г", uid, (int)Math.round(66.3), (int)Math.round(6.9), (int)Math.round(1.4)));
        appRepository.insertFood(new FoodEntity(0, "", "Мука рисовая", 356, "100г", uid, (int)Math.round(80.2), (int)Math.round(7.4), (int)Math.round(0.6)));
        appRepository.insertFood(new FoodEntity(0, "", "Овёс (зерно)", 316, "100г", uid, (int)Math.round(55.1), (int)Math.round(10), (int)Math.round(6.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Оладьи", 213, "100г", uid, (int)Math.round(31.6), (int)Math.round(6.5), (int)Math.round(6.6)));
        appRepository.insertFood(new FoodEntity(0, "", "Отруби овсяные", 246, "100г", uid, (int)Math.round(66.2), (int)Math.round(17.3), (int)Math.round(7)));
        appRepository.insertFood(new FoodEntity(0, "", "Отруби пшеничные", 165, "100г", uid, (int)Math.round(16.6), (int)Math.round(16), (int)Math.round(3.8)));
        appRepository.insertFood(new FoodEntity(0, "", "Печенье сахарное", 417, "100г", uid, (int)Math.round(74.4), (int)Math.round(7.5), (int)Math.round(9.8)));
        appRepository.insertFood(new FoodEntity(0, "", "Печенье сдобное", 451, "100г", uid, (int)Math.round(68.5), (int)Math.round(6.4), (int)Math.round(16.8)));
        appRepository.insertFood(new FoodEntity(0, "", "Пряники заварные", 366, "100г", uid, (int)Math.round(75), (int)Math.round(5.9), (int)Math.round(4.7)));
        appRepository.insertFood(new FoodEntity(0, "", "Пшеница (зерно, мягкий сорт)", 305, "100г", uid, (int)Math.round(59.5), (int)Math.round(11.8), (int)Math.round(2.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Пшеница (зерно, твердый сорт)", 304, "100г", uid, (int)Math.round(57.5), (int)Math.round(13), (int)Math.round(2.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Рис (зерно)", 303, "100г", uid, (int)Math.round(62.3), (int)Math.round(7.5), (int)Math.round(2.6)));
        appRepository.insertFood(new FoodEntity(0, "", "Рожь (зерно)", 283, "100г", uid, (int)Math.round(55.8), (int)Math.round(9.9), (int)Math.round(2.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Сухари сливочные", 399, "100г", uid, (int)Math.round(66.7), (int)Math.round(8.5), (int)Math.round(10.8)));
        appRepository.insertFood(new FoodEntity(0, "", "Сушки простые", 339, "100г", uid, (int)Math.round(71.2), (int)Math.round(10.7), (int)Math.round(1.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Хлеб бородинский", 201, "100г", uid, (int)Math.round(39.8), (int)Math.round(6.8), (int)Math.round(1.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Хлеб пшеничный (из муки 1 сорта)", 235, "100г", uid, (int)Math.round(48.3), (int)Math.round(7.9), (int)Math.round(1)));
        appRepository.insertFood(new FoodEntity(0, "", "Хлеб пшеничный (из муки в/с)", 235, "100г", uid, (int)Math.round(49.2), (int)Math.round(7.6), (int)Math.round(0)));
        appRepository.insertFood(new FoodEntity(0, "", "Хлеб пшеничный (из обойной муки)", 174, "100г", uid, (int)Math.round(33.4), (int)Math.round(6.6), (int)Math.round(1.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Хлеб рижский", 232, "100г", uid, (int)Math.round(49.4), (int)Math.round(5.6), (int)Math.round(1.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Хлеб цельнозерновой", 247, "100г", uid, (int)Math.round(41.3), (int)Math.round(13), (int)Math.round(3.4)));
        appRepository.insertFood(new FoodEntity(0, "", "Хлебцы с отрубями", 242, "100г", uid, (int)Math.round(46.3), (int)Math.round(8.2), (int)Math.round(2.6)));
        appRepository.insertFood(new FoodEntity(0, "", "Хлопья овсяные Геркулес", 352, "100г", uid, (int)Math.round(61.8), (int)Math.round(12.3), (int)Math.round(6.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Ячмень (зерно)", 288, "100г", uid, (int)Math.round(56.4), (int)Math.round(10.3), (int)Math.round(2.4)));
        appRepository.insertFood(new FoodEntity(0, "", "Горох (лущеный)", 299, "100г", uid, (int)Math.round(48.1), (int)Math.round(23), (int)Math.round(1.6)));
        appRepository.insertFood(new FoodEntity(0, "", "Горох зелёный (свежий)", 55, "100г", uid, (int)Math.round(8.3), (int)Math.round(5), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Зелёный горошек (консервы)", 40, "100г", uid, (int)Math.round(6.5), (int)Math.round(3.1), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Маш", 300, "100г", uid, (int)Math.round(46), (int)Math.round(23.5), (int)Math.round(2)));
        appRepository.insertFood(new FoodEntity(0, "", "Нут", 309, "100г", uid, (int)Math.round(46.1), (int)Math.round(20.1), (int)Math.round(4.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Соя (зерно)", 364, "100г", uid, (int)Math.round(17.3), (int)Math.round(34.9), (int)Math.round(17.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Суп фасолевый", 54, "100г", uid, (int)Math.round(6.9), (int)Math.round(3), (int)Math.round(1.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Фасоль (зерно)", 298, "100г", uid, (int)Math.round(47), (int)Math.round(21), (int)Math.round(2)));
        appRepository.insertFood(new FoodEntity(0, "", "Фасоль (стручковая)", 23, "100г", uid, (int)Math.round(3), (int)Math.round(2.5), (int)Math.round(0.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Чечевица (зерно)", 295, "100г", uid, (int)Math.round(46.3), (int)Math.round(24), (int)Math.round(1.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Арахис", 552, "100г", uid, (int)Math.round(9.9), (int)Math.round(26.3), (int)Math.round(45.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Грецкий орех", 656, "100г", uid, (int)Math.round(11.1), (int)Math.round(16.2), (int)Math.round(60.8)));
        appRepository.insertFood(new FoodEntity(0, "", "Желуди сушёные", 509, "100г", uid, (int)Math.round(53.6), (int)Math.round(8.1), (int)Math.round(31.4)));
        appRepository.insertFood(new FoodEntity(0, "", "Кедровый орех", 875, "100г", uid, (int)Math.round(13.1), (int)Math.round(13.7), (int)Math.round(68.4)));
        appRepository.insertFood(new FoodEntity(0, "", "Кешью", 600, "100г", uid, (int)Math.round(22.5), (int)Math.round(18.5), (int)Math.round(48.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Кунжут", 565, "100г", uid, (int)Math.round(12.2), (int)Math.round(19.4), (int)Math.round(48.7)));
        appRepository.insertFood(new FoodEntity(0, "", "Миндаль", 609, "100г", uid, (int)Math.round(13), (int)Math.round(18.6), (int)Math.round(53.7)));
        appRepository.insertFood(new FoodEntity(0, "", "Семена подсолнечника (семечки)", 601, "100г", uid, (int)Math.round(10.5), (int)Math.round(20.7), (int)Math.round(52.9)));
        appRepository.insertFood(new FoodEntity(0, "", "Фисташки", 560, "100г", uid, (int)Math.round(27.2), (int)Math.round(20.2), (int)Math.round(45.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Фундук", 653, "100г", uid, (int)Math.round(9.3), (int)Math.round(13), (int)Math.round(62.6)));
        appRepository.insertFood(new FoodEntity(0, "", "Базилик (зелень)", 23, "100г", uid, (int)Math.round(2.7), (int)Math.round(3.2), (int)Math.round(0.6)));
        appRepository.insertFood(new FoodEntity(0, "", "Баклажаны", 24, "100г", uid, (int)Math.round(4.5), (int)Math.round(1.2), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Брюква", 37, "100г", uid, (int)Math.round(7.7), (int)Math.round(1.2), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Запеканка картофельная", 136, "100г", uid, (int)Math.round(17.5), (int)Math.round(3), (int)Math.round(5.9)));
        appRepository.insertFood(new FoodEntity(0, "", "Икра из баклажанов (консервы)", 148, "100г", uid, (int)Math.round(5.1), (int)Math.round(1.7), (int)Math.round(13.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Икра кабачковая (консервы)", 119, "100г", uid, (int)Math.round(7.7), (int)Math.round(1.9), (int)Math.round(8.9)));
        appRepository.insertFood(new FoodEntity(0, "", "Имбирь (корень)", 80, "100г", uid, (int)Math.round(17.8), (int)Math.round(1.8), (int)Math.round(0.8)));
        appRepository.insertFood(new FoodEntity(0, "", "Кабачки", 24, "100г", uid, (int)Math.round(4.6), (int)Math.round(0.6), (int)Math.round(0.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Капуста белокочанная", 28, "100г", uid, (int)Math.round(4.7), (int)Math.round(1.8), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Капуста белокочанная тушёная", 75, "100г", uid, (int)Math.round(9.2), (int)Math.round(2), (int)Math.round(3.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Капуста брокколи", 34, "100г", uid, (int)Math.round(6.6), (int)Math.round(2.8), (int)Math.round(0.4)));
        appRepository.insertFood(new FoodEntity(0, "", "Капуста брюссельская", 35, "100г", uid, (int)Math.round(3.1), (int)Math.round(4.8), (int)Math.round(0.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Капуста квашеная", 23, "100г", uid, (int)Math.round(3), (int)Math.round(1.8), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Капуста кольраби", 44, "100г", uid, (int)Math.round(7.9), (int)Math.round(2.8), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Капуста краснокочанная", 26, "100г", uid, (int)Math.round(5.1), (int)Math.round(0.8), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Капуста пекинская", 16, "100г", uid, (int)Math.round(2), (int)Math.round(1.2), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Капуста савойская", 28, "100г", uid, (int)Math.round(6), (int)Math.round(1.2), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Капуста цветная", 30, "100г", uid, (int)Math.round(4.2), (int)Math.round(2.5), (int)Math.round(0.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Картофель", 77, "100г", uid, (int)Math.round(16.3), (int)Math.round(2), (int)Math.round(0.4)));
        appRepository.insertFood(new FoodEntity(0, "", "Картофель жареный", 192, "100г", uid, (int)Math.round(23.5), (int)Math.round(2.8), (int)Math.round(9.6)));
        appRepository.insertFood(new FoodEntity(0, "", "Каша из тыквы", 87, "100г", uid, (int)Math.round(15.7), (int)Math.round(2.1), (int)Math.round(1.7)));
        appRepository.insertFood(new FoodEntity(0, "", "Кинза (зелень)", 23, "100г", uid, (int)Math.round(3.7), (int)Math.round(2.1), (int)Math.round(0.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Кресс-салат (зелень)", 32, "100г", uid, (int)Math.round(5.5), (int)Math.round(2.6), (int)Math.round(0.7)));
        appRepository.insertFood(new FoodEntity(0, "", "Листья одуванчика (зелень)", 45, "100г", uid, (int)Math.round(9.2), (int)Math.round(2.7), (int)Math.round(0.7)));
        appRepository.insertFood(new FoodEntity(0, "", "Лук зелёный (перо)", 20, "100г", uid, (int)Math.round(3.2), (int)Math.round(1.3), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Лук порей", 36, "100г", uid, (int)Math.round(6.3), (int)Math.round(2), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Лук репчатый", 41, "100г", uid, (int)Math.round(8.2), (int)Math.round(1.4), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Морковь", 35, "100г", uid, (int)Math.round(6.9), (int)Math.round(1.3), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Морковь отварная", 33, "100г", uid, (int)Math.round(6.4), (int)Math.round(1.3), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Морская капуста", 25, "100г", uid, (int)Math.round(3), (int)Math.round(0.9), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Огурец", 14, "100г", uid, (int)Math.round(2.5), (int)Math.round(0.8), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Огурцы солёные", 13, "100г", uid, (int)Math.round(1.7), (int)Math.round(0.8), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Папоротник", 34, "100г", uid, (int)Math.round(5.5), (int)Math.round(4.6), (int)Math.round(0.4)));
        appRepository.insertFood(new FoodEntity(0, "", "Пастернак (корень)", 47, "100г", uid, (int)Math.round(9.2), (int)Math.round(1.4), (int)Math.round(0.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Перец сладкий (болгарский)", 26, "100г", uid, (int)Math.round(4.9), (int)Math.round(1.3), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Петрушка (зелень)", 49, "100г", uid, (int)Math.round(7.6), (int)Math.round(3.7), (int)Math.round(0.4)));
        appRepository.insertFood(new FoodEntity(0, "", "Петрушка (корень)", 51, "100г", uid, (int)Math.round(10.1), (int)Math.round(1.5), (int)Math.round(0.6)));
        appRepository.insertFood(new FoodEntity(0, "", "Помидор (томат)", 24, "100г", uid, (int)Math.round(3.8), (int)Math.round(1.1), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Ревень (зелень)", 16, "100г", uid, (int)Math.round(2.5), (int)Math.round(0.7), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Редис", 20, "100г", uid, (int)Math.round(3.4), (int)Math.round(1.2), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Редька чёрная", 36, "100г", uid, (int)Math.round(6.7), (int)Math.round(1.9), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Репа", 32, "100г", uid, (int)Math.round(6.2), (int)Math.round(1.5), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Салат листовой (зелень)", 16, "100г", uid, (int)Math.round(2), (int)Math.round(1.5), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Свекла", 42, "100г", uid, (int)Math.round(8.8), (int)Math.round(1.5), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Свекла отварная", 48, "100г", uid, (int)Math.round(9.8), (int)Math.round(1.8), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Сельдерей (зелень)", 13, "100г", uid, (int)Math.round(2.1), (int)Math.round(0.9), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Сельдерей (корень)", 34, "100г", uid, (int)Math.round(6.5), (int)Math.round(1.3), (int)Math.round(0.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Спаржа (зелень)", 21, "100г", uid, (int)Math.round(3.1), (int)Math.round(1.9), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Томатная паста", 102, "100г", uid, (int)Math.round(19), (int)Math.round(4.8), (int)Math.round(0)));
        appRepository.insertFood(new FoodEntity(0, "", "Топинамбур", 61, "100г", uid, (int)Math.round(12.8), (int)Math.round(2.1), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Тыква", 22, "100г", uid, (int)Math.round(4.4), (int)Math.round(1), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Тыква отварная", 26, "100г", uid, (int)Math.round(4.9), (int)Math.round(1.2), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Укроп (зелень)", 40, "100г", uid, (int)Math.round(6.3), (int)Math.round(2.5), (int)Math.round(0.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Хрен (корень)", 59, "100г", uid, (int)Math.round(10.5), (int)Math.round(3.2), (int)Math.round(0.4)));
        appRepository.insertFood(new FoodEntity(0, "", "Чеснок", 149, "100г", uid, (int)Math.round(29.9), (int)Math.round(6.5), (int)Math.round(0.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Шпинат (зелень)", 23, "100г", uid, (int)Math.round(2), (int)Math.round(2.9), (int)Math.round(0.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Щавель (зелень)", 22, "100г", uid, (int)Math.round(2.9), (int)Math.round(1.5), (int)Math.round(0.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Абрикос", 44, "100г", uid, (int)Math.round(9), (int)Math.round(0.9), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Авокадо", 160, "100г", uid, (int)Math.round(1.8), (int)Math.round(2), (int)Math.round(14.6)));
        appRepository.insertFood(new FoodEntity(0, "", "Айва", 48, "100г", uid, (int)Math.round(9.6), (int)Math.round(0.6), (int)Math.round(0.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Алыча", 34, "100г", uid, (int)Math.round(7.9), (int)Math.round(0.2), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Ананас", 52, "100г", uid, (int)Math.round(11.5), (int)Math.round(0.4), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Апельсин", 43, "100г", uid, (int)Math.round(8.1), (int)Math.round(0.9), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Арбуз", 27, "100г", uid, (int)Math.round(5.8), (int)Math.round(0.6), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Банан", 96, "100г", uid, (int)Math.round(21), (int)Math.round(1.5), (int)Math.round(0.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Брусника", 46, "100г", uid, (int)Math.round(8.2), (int)Math.round(0.7), (int)Math.round(0.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Варенье из клубники", 285, "100г", uid, (int)Math.round(74), (int)Math.round(0.3), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Варенье из малины", 273, "100г", uid, (int)Math.round(70.4), (int)Math.round(0.6), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Виноград", 72, "100г", uid, (int)Math.round(15.4), (int)Math.round(0.6), (int)Math.round(0.6)));
        appRepository.insertFood(new FoodEntity(0, "", "Вишня", 52, "100г", uid, (int)Math.round(10.6), (int)Math.round(0.8), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Голубика", 39, "100г", uid, (int)Math.round(6.6), (int)Math.round(1), (int)Math.round(0.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Гранат", 72, "100г", uid, (int)Math.round(14.5), (int)Math.round(0.7), (int)Math.round(0.6)));
        appRepository.insertFood(new FoodEntity(0, "", "Грейпфрут", 35, "100г", uid, (int)Math.round(6.5), (int)Math.round(0.7), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Груша", 47, "100г", uid, (int)Math.round(10.3), (int)Math.round(0.4), (int)Math.round(0.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Дуриан", 147, "100г", uid, (int)Math.round(27.1), (int)Math.round(1.47), (int)Math.round(5.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Дыня", 35, "100г", uid, (int)Math.round(7.4), (int)Math.round(0.6), (int)Math.round(0.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Ежевика", 34, "100г", uid, (int)Math.round(4.4), (int)Math.round(1.5), (int)Math.round(0.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Земляника", 41, "100г", uid, (int)Math.round(7.5), (int)Math.round(0.8), (int)Math.round(0.4)));
        appRepository.insertFood(new FoodEntity(0, "", "Инжир свежий", 54, "100г", uid, (int)Math.round(12), (int)Math.round(0.7), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Киви", 47, "100г", uid, (int)Math.round(8.1), (int)Math.round(0.8), (int)Math.round(0.4)));
        appRepository.insertFood(new FoodEntity(0, "", "Клюква", 28, "100г", uid, (int)Math.round(3.7), (int)Math.round(0.5), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Крыжовник", 45, "100г", uid, (int)Math.round(9.1), (int)Math.round(0.7), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Лимон", 34, "100г", uid, (int)Math.round(3), (int)Math.round(0.9), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Малина", 46, "100г", uid, (int)Math.round(8.3), (int)Math.round(0.8), (int)Math.round(0.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Манго", 60, "100г", uid, (int)Math.round(15), (int)Math.round(0.8), (int)Math.round(0.4)));
        appRepository.insertFood(new FoodEntity(0, "", "Мандарин", 38, "100г", uid, (int)Math.round(7.5), (int)Math.round(0.8), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Морошка", 40, "100г", uid, (int)Math.round(7.4), (int)Math.round(0.8), (int)Math.round(0.9)));
        appRepository.insertFood(new FoodEntity(0, "", "Нектарин", 44, "100г", uid, (int)Math.round(10.5), (int)Math.round(1.1), (int)Math.round(0.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Облепиха", 82, "100г", uid, (int)Math.round(5.7), (int)Math.round(1.2), (int)Math.round(5.4)));
        appRepository.insertFood(new FoodEntity(0, "", "Папайя", 43, "100г", uid, (int)Math.round(10.8), (int)Math.round(0.5), (int)Math.round(0.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Персик", 45, "100г", uid, (int)Math.round(9.5), (int)Math.round(0.9), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Помело", 38, "100г", uid, (int)Math.round(9.6), (int)Math.round(0.8), (int)Math.round(0)));
        appRepository.insertFood(new FoodEntity(0, "", "Рябина красная", 50, "100г", uid, (int)Math.round(8.9), (int)Math.round(1.4), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Рябина черноплодная", 55, "100г", uid, (int)Math.round(10.9), (int)Math.round(1.5), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Слива", 49, "100г", uid, (int)Math.round(9.6), (int)Math.round(0.8), (int)Math.round(0.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Смородина белая", 42, "100г", uid, (int)Math.round(8), (int)Math.round(0.5), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Смородина красная", 43, "100г", uid, (int)Math.round(7.7), (int)Math.round(0.6), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Смородина чёрная", 44, "100г", uid, (int)Math.round(7.3), (int)Math.round(1), (int)Math.round(0.4)));
        appRepository.insertFood(new FoodEntity(0, "", "Фейхоа", 61, "100г", uid, (int)Math.round(15.2), (int)Math.round(0.7), (int)Math.round(0.4)));
        appRepository.insertFood(new FoodEntity(0, "", "Хурма", 67, "100г", uid, (int)Math.round(15.3), (int)Math.round(0.5), (int)Math.round(0.4)));
        appRepository.insertFood(new FoodEntity(0, "", "Черешня", 52, "100г", uid, (int)Math.round(10.6), (int)Math.round(1.1), (int)Math.round(0.4)));
        appRepository.insertFood(new FoodEntity(0, "", "Черника", 44, "100г", uid, (int)Math.round(7.6), (int)Math.round(1.1), (int)Math.round(0.6)));
        appRepository.insertFood(new FoodEntity(0, "", "Шиповник", 109, "100г", uid, (int)Math.round(22.4), (int)Math.round(1.6), (int)Math.round(0.7)));
        appRepository.insertFood(new FoodEntity(0, "", "Яблоки", 47, "100г", uid, (int)Math.round(9.8), (int)Math.round(0.4), (int)Math.round(0.4)));
        appRepository.insertFood(new FoodEntity(0, "", "Груша сушёная", 270, "100г", uid, (int)Math.round(62.6), (int)Math.round(2.3), (int)Math.round(0.6)));
        appRepository.insertFood(new FoodEntity(0, "", "Изюм", 281, "100г", uid, (int)Math.round(65.8), (int)Math.round(2.3), (int)Math.round(0.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Инжир сушёный", 257, "100г", uid, (int)Math.round(57.9), (int)Math.round(3.1), (int)Math.round(0.8)));
        appRepository.insertFood(new FoodEntity(0, "", "Курага", 232, "100г", uid, (int)Math.round(51), (int)Math.round(5.2), (int)Math.round(0.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Персик сушёный", 254, "100г", uid, (int)Math.round(57.7), (int)Math.round(3), (int)Math.round(0.4)));
        appRepository.insertFood(new FoodEntity(0, "", "Урюк", 242, "100г", uid, (int)Math.round(53), (int)Math.round(5), (int)Math.round(0.4)));
        appRepository.insertFood(new FoodEntity(0, "", "Финики", 292, "100г", uid, (int)Math.round(69.2), (int)Math.round(2.5), (int)Math.round(0.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Чернослив", 256, "100г", uid, (int)Math.round(57.5), (int)Math.round(2.3), (int)Math.round(0.7)));
        appRepository.insertFood(new FoodEntity(0, "", "Яблоки сушёные", 253, "100г", uid, (int)Math.round(59), (int)Math.round(2.2), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Гриб вешенка", 33, "100г", uid, (int)Math.round(6.1), (int)Math.round(3.3), (int)Math.round(0.4)));
        appRepository.insertFood(new FoodEntity(0, "", "Гриб рыжик", 17, "100г", uid, (int)Math.round(0.5), (int)Math.round(1.9), (int)Math.round(0.8)));
        appRepository.insertFood(new FoodEntity(0, "", "Гриб сморчок", 31, "100г", uid, (int)Math.round(5.1), (int)Math.round(3.1), (int)Math.round(0.6)));
        appRepository.insertFood(new FoodEntity(0, "", "Грибы белые", 34, "100г", uid, (int)Math.round(1.1), (int)Math.round(3.7), (int)Math.round(1.7)));
        appRepository.insertFood(new FoodEntity(0, "", "Грибы белые сушёные", 286, "100г", uid, (int)Math.round(9), (int)Math.round(30.3), (int)Math.round(14.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Грибы лисички", 19, "100г", uid, (int)Math.round(1), (int)Math.round(1.5), (int)Math.round(1)));
        appRepository.insertFood(new FoodEntity(0, "", "Грибы опята", 22, "100г", uid, (int)Math.round(0.5), (int)Math.round(2.2), (int)Math.round(1.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Грибы подберёзовики", 20, "100г", uid, (int)Math.round(1.2), (int)Math.round(2.1), (int)Math.round(0.8)));
        appRepository.insertFood(new FoodEntity(0, "", "Грибы подосиновики", 22, "100г", uid, (int)Math.round(1.2), (int)Math.round(3.3), (int)Math.round(0.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Грибы сыроежки", 19, "100г", uid, (int)Math.round(1.5), (int)Math.round(1.7), (int)Math.round(0.7)));
        appRepository.insertFood(new FoodEntity(0, "", "Грибы шампиньоны", 27, "100г", uid, (int)Math.round(0.1), (int)Math.round(4.3), (int)Math.round(1)));
        appRepository.insertFood(new FoodEntity(0, "", "Грибы шиитаке", 34, "100г", uid, (int)Math.round(6.8), (int)Math.round(2.2), (int)Math.round(0.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Сок абрикосовый", 55, "100г", uid, (int)Math.round(12.7), (int)Math.round(0.5), (int)Math.round(0)));
        appRepository.insertFood(new FoodEntity(0, "", "Сок ананасовый", 52, "100г", uid, (int)Math.round(11.8), (int)Math.round(0.3), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Сок апельсиновый", 45, "100г", uid, (int)Math.round(10.4), (int)Math.round(0.7), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Сок виноградный", 70, "100г", uid, (int)Math.round(16.3), (int)Math.round(0.3), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Сок вишнёвый", 51, "100г", uid, (int)Math.round(11.4), (int)Math.round(0.7), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Сок гранатовый", 56, "100г", uid, (int)Math.round(14.2), (int)Math.round(0.3), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Сок грейпфрутовый", 38, "100г", uid, (int)Math.round(7.9), (int)Math.round(0.3), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Сок капустный", 33, "100г", uid, (int)Math.round(7.1), (int)Math.round(1.2), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Сок лимонный", 22, "100г", uid, (int)Math.round(6.9), (int)Math.round(0.3), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Сок мандариновый", 45, "100г", uid, (int)Math.round(9.8), (int)Math.round(0.8), (int)Math.round(0)));
        appRepository.insertFood(new FoodEntity(0, "", "Сок морковный", 56, "100г", uid, (int)Math.round(12.6), (int)Math.round(1.1), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Сок персиковый", 68, "100г", uid, (int)Math.round(16.5), (int)Math.round(0.3), (int)Math.round(0)));
        appRepository.insertFood(new FoodEntity(0, "", "Сок свекольный", 61, "100г", uid, (int)Math.round(14), (int)Math.round(1), (int)Math.round(0)));
        appRepository.insertFood(new FoodEntity(0, "", "Сок томатный", 18, "100г", uid, (int)Math.round(2.9), (int)Math.round(1), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Сок яблочный", 46, "100г", uid, (int)Math.round(10.1), (int)Math.round(0.5), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Масло арахисовое", 899, "100г", uid, (int)Math.round(0), (int)Math.round(0), (int)Math.round(99.9)));
        appRepository.insertFood(new FoodEntity(0, "", "Масло подсолнечное", 899, "100г", uid, (int)Math.round(0), (int)Math.round(0), (int)Math.round(99.9)));
        appRepository.insertFood(new FoodEntity(0, "", "Масло кокосовое", 899, "100г", uid, (int)Math.round(0), (int)Math.round(0), (int)Math.round(99.9)));
        appRepository.insertFood(new FoodEntity(0, "", "Рыбий жир (из печени трески)", 898, "100г", uid, (int)Math.round(0), (int)Math.round(0), (int)Math.round(99.8)));
        appRepository.insertFood(new FoodEntity(0, "", "Масло горчичное", 898, "100г", uid, (int)Math.round(0), (int)Math.round(0), (int)Math.round(99.8)));
        appRepository.insertFood(new FoodEntity(0, "", "Масло оливковое", 898, "100г", uid, (int)Math.round(0), (int)Math.round(0), (int)Math.round(99.8)));
        appRepository.insertFood(new FoodEntity(0, "", "Масло льняное", 898, "100г", uid, (int)Math.round(0), (int)Math.round(0), (int)Math.round(99.8)));
        appRepository.insertFood(new FoodEntity(0, "", "Масло топлёное", 892, "100г", uid, (int)Math.round(0), (int)Math.round(0.2), (int)Math.round(99)));
        appRepository.insertFood(new FoodEntity(0, "", "Кедровый орех", 875, "100г", uid, (int)Math.round(13.1), (int)Math.round(13.7), (int)Math.round(68.4)));
        appRepository.insertFood(new FoodEntity(0, "", "Масло сладко-сливочное несолёное", 748, "100г", uid, (int)Math.round(0.8), (int)Math.round(0.5), (int)Math.round(82.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Маргарин сливочный", 743, "100г", uid, (int)Math.round(1), (int)Math.round(0.3), (int)Math.round(82)));
        appRepository.insertFood(new FoodEntity(0, "", "Масло сливочное", 661, "100г", uid, (int)Math.round(1.3), (int)Math.round(0.8), (int)Math.round(72.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Грецкий орех", 656, "100г", uid, (int)Math.round(11.1), (int)Math.round(16.2), (int)Math.round(60.8)));
        appRepository.insertFood(new FoodEntity(0, "", "Фундук", 653, "100г", uid, (int)Math.round(9.3), (int)Math.round(13), (int)Math.round(62.6)));
        appRepository.insertFood(new FoodEntity(0, "", "Майонез Провансаль", 629, "100г", uid, (int)Math.round(3.7), (int)Math.round(2.8), (int)Math.round(67)));
        appRepository.insertFood(new FoodEntity(0, "", "Печень трески (консервы)", 613, "100г", uid, (int)Math.round(1.2), (int)Math.round(4.2), (int)Math.round(65.7)));
        appRepository.insertFood(new FoodEntity(0, "", "Миндаль", 609, "100г", uid, (int)Math.round(13), (int)Math.round(18.6), (int)Math.round(53.7)));
        appRepository.insertFood(new FoodEntity(0, "", "Колбаса зернистая", 606, "100г", uid, (int)Math.round(0.3), (int)Math.round(9.9), (int)Math.round(62.8)));
        appRepository.insertFood(new FoodEntity(0, "", "Семена подсолнечника (семечки)", 601, "100г", uid, (int)Math.round(10.5), (int)Math.round(20.7), (int)Math.round(52.9)));
        appRepository.insertFood(new FoodEntity(0, "", "Кешью", 600, "100г", uid, (int)Math.round(22.5), (int)Math.round(18.5), (int)Math.round(48.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Сливки сухие 42%", 577, "100г", uid, (int)Math.round(30.2), (int)Math.round(19), (int)Math.round(42)));
        appRepository.insertFood(new FoodEntity(0, "", "Кунжут", 565, "100г", uid, (int)Math.round(12.2), (int)Math.round(19.4), (int)Math.round(48.7)));
        appRepository.insertFood(new FoodEntity(0, "", "Фисташки", 560, "100г", uid, (int)Math.round(27.2), (int)Math.round(20.2), (int)Math.round(45.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Шоколад молочный", 554, "100г", uid, (int)Math.round(50.4), (int)Math.round(9.8), (int)Math.round(34.7)));
        appRepository.insertFood(new FoodEntity(0, "", "Арахис", 552, "100г", uid, (int)Math.round(9.9), (int)Math.round(26.3), (int)Math.round(45.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Вафли", 542, "100г", uid, (int)Math.round(62.5), (int)Math.round(3.9), (int)Math.round(30.6)));
        appRepository.insertFood(new FoodEntity(0, "", "Яичный порошок", 542, "100г", uid, (int)Math.round(4.5), (int)Math.round(46), (int)Math.round(37.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Шоколад горький", 539, "100г", uid, (int)Math.round(48.2), (int)Math.round(6.2), (int)Math.round(35.4)));
        appRepository.insertFood(new FoodEntity(0, "", "Халва подсолнечная", 516, "100г", uid, (int)Math.round(54), (int)Math.round(11.6), (int)Math.round(29.7)));
        appRepository.insertFood(new FoodEntity(0, "", "Желуди сушёные", 509, "100г", uid, (int)Math.round(53.6), (int)Math.round(8.1), (int)Math.round(31.4)));
        appRepository.insertFood(new FoodEntity(0, "", "Конфеты шоколадные", 491, "100г", uid, (int)Math.round(59.2), (int)Math.round(4), (int)Math.round(26.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Колбаса брауншвейгская", 491, "100г", uid, (int)Math.round(0.2), (int)Math.round(27.7), (int)Math.round(42.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Мясо (свинина жирная)", 491, "100г", uid, (int)Math.round(0), (int)Math.round(11.7), (int)Math.round(49.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Пирожное песочное с кремом", 485, "100г", uid, (int)Math.round(52.1), (int)Math.round(5.1), (int)Math.round(28.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Молоко сухое 25%", 483, "100г", uid, (int)Math.round(39.3), (int)Math.round(24.2), (int)Math.round(25)));
        appRepository.insertFood(new FoodEntity(0, "", "Колбаски охотничьи", 463, "100г", uid, (int)Math.round(0.3), (int)Math.round(25.3), (int)Math.round(40)));
        appRepository.insertFood(new FoodEntity(0, "", "Колбаса сервелат", 461, "100г", uid, (int)Math.round(0.2), (int)Math.round(24), (int)Math.round(40.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Печенье сдобное", 451, "100г", uid, (int)Math.round(68.5), (int)Math.round(6.4), (int)Math.round(16.8)));
        appRepository.insertFood(new FoodEntity(0, "", "Печенье сдобное", 451, "100г", uid, (int)Math.round(68.5), (int)Math.round(6.4), (int)Math.round(16.8)));
        appRepository.insertFood(new FoodEntity(0, "", "Пирожное заварное с кремом (трубочка)", 433, "100г", uid, (int)Math.round(48.8), (int)Math.round(4.4), (int)Math.round(24.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Молоко сухое 15%", 432, "100г", uid, (int)Math.round(44.7), (int)Math.round(28.5), (int)Math.round(15)));
        appRepository.insertFood(new FoodEntity(0, "", "Печенье сахарное", 417, "100г", uid, (int)Math.round(74.4), (int)Math.round(7.5), (int)Math.round(9.8)));
        appRepository.insertFood(new FoodEntity(0, "", "Печенье сахарное", 417, "100г", uid, (int)Math.round(74.4), (int)Math.round(7.5), (int)Math.round(9.8)));
        appRepository.insertFood(new FoodEntity(0, "", "Сырки глазированные 27,7% жирности", 413, "100г", uid, (int)Math.round(32.6), (int)Math.round(7.9), (int)Math.round(27.7)));
        appRepository.insertFood(new FoodEntity(0, "", "Колбаса московская (копчёная)", 406, "100г", uid, (int)Math.round(0.2), (int)Math.round(19.1), (int)Math.round(36.6)));
        appRepository.insertFood(new FoodEntity(0, "", "Сухари сливочные", 399, "100г", uid, (int)Math.round(66.7), (int)Math.round(8.5), (int)Math.round(10.8)));
        appRepository.insertFood(new FoodEntity(0, "", "Сахар-песок", 399, "100г", uid, (int)Math.round(99.8), (int)Math.round(0), (int)Math.round(0)));
        appRepository.insertFood(new FoodEntity(0, "", "Сливки сгущённые с сахаром 19%", 392, "100г", uid, (int)Math.round(47), (int)Math.round(8), (int)Math.round(19)));
        appRepository.insertFood(new FoodEntity(0, "", "Сыр Пармезан", 392, "100г", uid, (int)Math.round(0.8), (int)Math.round(35.7), (int)Math.round(25.8)));
        appRepository.insertFood(new FoodEntity(0, "", "Сыр Швейцарский 50%", 391, "100г", uid, (int)Math.round(0), (int)Math.round(24.6), (int)Math.round(31.6)));
        appRepository.insertFood(new FoodEntity(0, "", "Соль поваренная", 0, "100г", uid, (int)Math.round(0), (int)Math.round(0), (int)Math.round(0)));
        appRepository.insertFood(new FoodEntity(0, "", "Огурцы солёные", 13, "100г", uid, (int)Math.round(1.7), (int)Math.round(0.8), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Сельдерей (зелень)", 13, "100г", uid, (int)Math.round(2.1), (int)Math.round(0.9), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Огурец", 14, "100г", uid, (int)Math.round(2.5), (int)Math.round(0.8), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Капуста пекинская", 16, "100г", uid, (int)Math.round(2), (int)Math.round(1.2), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Ревень (зелень)", 16, "100г", uid, (int)Math.round(2.5), (int)Math.round(0.7), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Салат листовой (зелень)", 16, "100г", uid, (int)Math.round(2), (int)Math.round(1.5), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Гриб рыжик", 17, "100г", uid, (int)Math.round(0.5), (int)Math.round(1.9), (int)Math.round(0.8)));
        appRepository.insertFood(new FoodEntity(0, "", "Сок томатный", 18, "100г", uid, (int)Math.round(2.9), (int)Math.round(1), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Грибы сыроежки", 19, "100г", uid, (int)Math.round(1.5), (int)Math.round(1.7), (int)Math.round(0.7)));
        appRepository.insertFood(new FoodEntity(0, "", "Грибы лисички", 19, "100г", uid, (int)Math.round(1), (int)Math.round(1.5), (int)Math.round(1)));
        appRepository.insertFood(new FoodEntity(0, "", "Грибы подберёзовики", 20, "100г", uid, (int)Math.round(1.2), (int)Math.round(2.1), (int)Math.round(0.8)));
        appRepository.insertFood(new FoodEntity(0, "", "Лук зелёный (перо)", 20, "100г", uid, (int)Math.round(3.2), (int)Math.round(1.3), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Редис", 20, "100г", uid, (int)Math.round(3.4), (int)Math.round(1.2), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Спаржа (зелень)", 21, "100г", uid, (int)Math.round(3.1), (int)Math.round(1.9), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Грибы подосиновики", 22, "100г", uid, (int)Math.round(1.2), (int)Math.round(3.3), (int)Math.round(0.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Грибы опята", 22, "100г", uid, (int)Math.round(0.5), (int)Math.round(2.2), (int)Math.round(1.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Тыква", 22, "100г", uid, (int)Math.round(4.4), (int)Math.round(1), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Сок лимонный", 22, "100г", uid, (int)Math.round(6.9), (int)Math.round(0.3), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Щавель (зелень)", 22, "100г", uid, (int)Math.round(2.9), (int)Math.round(1.5), (int)Math.round(0.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Кинза (зелень)", 23, "100г", uid, (int)Math.round(3.7), (int)Math.round(2.1), (int)Math.round(0.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Базилик (зелень)", 23, "100г", uid, (int)Math.round(2.7), (int)Math.round(3.2), (int)Math.round(0.6)));
        appRepository.insertFood(new FoodEntity(0, "", "Фасоль (стручковая)", 23, "100г", uid, (int)Math.round(3), (int)Math.round(2.5), (int)Math.round(0.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Капуста квашеная", 23, "100г", uid, (int)Math.round(3), (int)Math.round(1.8), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Шпинат (зелень)", 23, "100г", uid, (int)Math.round(2), (int)Math.round(2.9), (int)Math.round(0.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Помидор (томат)", 24, "100г", uid, (int)Math.round(3.8), (int)Math.round(1.1), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Баклажаны", 24, "100г", uid, (int)Math.round(4.5), (int)Math.round(1.2), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Кабачки", 24, "100г", uid, (int)Math.round(4.6), (int)Math.round(0.6), (int)Math.round(0.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Морская капуста", 25, "100г", uid, (int)Math.round(3), (int)Math.round(0.9), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Тыква отварная", 26, "100г", uid, (int)Math.round(4.9), (int)Math.round(1.2), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Капуста краснокочанная", 26, "100г", uid, (int)Math.round(5.1), (int)Math.round(0.8), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Перец сладкий (болгарский)", 26, "100г", uid, (int)Math.round(4.9), (int)Math.round(1.3), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Арбуз", 27, "100г", uid, (int)Math.round(5.8), (int)Math.round(0.6), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Грибы шампиньоны", 27, "100г", uid, (int)Math.round(0.1), (int)Math.round(4.3), (int)Math.round(1)));
        appRepository.insertFood(new FoodEntity(0, "", "Клюква", 28, "100г", uid, (int)Math.round(3.7), (int)Math.round(0.5), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Капуста савойская", 28, "100г", uid, (int)Math.round(6), (int)Math.round(1.2), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Капуста белокочанная", 28, "100г", uid, (int)Math.round(4.7), (int)Math.round(1.8), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Простокваша нежирная", 30, "100г", uid, (int)Math.round(3.8), (int)Math.round(3), (int)Math.round(0.05)));
        appRepository.insertFood(new FoodEntity(0, "", "Капуста цветная", 30, "100г", uid, (int)Math.round(4.2), (int)Math.round(2.5), (int)Math.round(0.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Гриб сморчок", 31, "100г", uid, (int)Math.round(5.1), (int)Math.round(3.1), (int)Math.round(0.6)));
        appRepository.insertFood(new FoodEntity(0, "", "Ацидофилин нежирный", 31, "100г", uid, (int)Math.round(3.9), (int)Math.round(3), (int)Math.round(0.05)));
        appRepository.insertFood(new FoodEntity(0, "", "Кефир нежирный", 31, "100г", uid, (int)Math.round(4), (int)Math.round(3), (int)Math.round(0.05)));
        appRepository.insertFood(new FoodEntity(0, "", "Кресс-салат (зелень)", 32, "100г", uid, (int)Math.round(5.5), (int)Math.round(2.6), (int)Math.round(0.7)));
        appRepository.insertFood(new FoodEntity(0, "", "Молоко нежирное", 32, "100г", uid, (int)Math.round(4.9), (int)Math.round(3), (int)Math.round(0.05)));
        appRepository.insertFood(new FoodEntity(0, "", "Репа", 32, "100г", uid, (int)Math.round(6.2), (int)Math.round(1.5), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Сок капустный", 33, "100г", uid, (int)Math.round(7.1), (int)Math.round(1.2), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Морковь отварная", 33, "100г", uid, (int)Math.round(6.4), (int)Math.round(1.3), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Гриб вешенка", 33, "100г", uid, (int)Math.round(6.1), (int)Math.round(3.3), (int)Math.round(0.4)));
        appRepository.insertFood(new FoodEntity(0, "", "Папоротник", 34, "100г", uid, (int)Math.round(5.5), (int)Math.round(4.6), (int)Math.round(0.4)));
        appRepository.insertFood(new FoodEntity(0, "", "Алыча", 34, "100г", uid, (int)Math.round(7.9), (int)Math.round(0.2), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Грибы белые", 34, "100г", uid, (int)Math.round(1.1), (int)Math.round(3.7), (int)Math.round(1.7)));
        appRepository.insertFood(new FoodEntity(0, "", "Капуста брокколи", 34, "100г", uid, (int)Math.round(6.6), (int)Math.round(2.8), (int)Math.round(0.4)));
        appRepository.insertFood(new FoodEntity(0, "", "Лимон", 34, "100г", uid, (int)Math.round(3), (int)Math.round(0.9), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Грибы шиитаке", 34, "100г", uid, (int)Math.round(6.8), (int)Math.round(2.2), (int)Math.round(0.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Ежевика", 34, "100г", uid, (int)Math.round(4.4), (int)Math.round(1.5), (int)Math.round(0.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Сельдерей (корень)", 34, "100г", uid, (int)Math.round(6.5), (int)Math.round(1.3), (int)Math.round(0.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Грейпфрут", 35, "100г", uid, (int)Math.round(6.5), (int)Math.round(0.7), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Морковь", 35, "100г", uid, (int)Math.round(6.9), (int)Math.round(1.3), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Дыня", 35, "100г", uid, (int)Math.round(7.4), (int)Math.round(0.6), (int)Math.round(0.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Капуста брюссельская", 35, "100г", uid, (int)Math.round(3.1), (int)Math.round(4.8), (int)Math.round(0.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Редька чёрная", 36, "100г", uid, (int)Math.round(6.7), (int)Math.round(1.9), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Лук порей", 36, "100г", uid, (int)Math.round(6.3), (int)Math.round(2), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Брюква", 37, "100г", uid, (int)Math.round(7.7), (int)Math.round(1.2), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Мандарин", 38, "100г", uid, (int)Math.round(7.5), (int)Math.round(0.8), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Сок грейпфрутовый", 38, "100г", uid, (int)Math.round(7.9), (int)Math.round(0.3), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Помело", 38, "100г", uid, (int)Math.round(9.6), (int)Math.round(0.8), (int)Math.round(0)));
        appRepository.insertFood(new FoodEntity(0, "", "Голубика", 39, "100г", uid, (int)Math.round(6.6), (int)Math.round(1), (int)Math.round(0.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Ацидофилин 1%", 40, "100г", uid, (int)Math.round(4), (int)Math.round(3), (int)Math.round(1)));
        appRepository.insertFood(new FoodEntity(0, "", "Зелёный горошек (консервы)", 40, "100г", uid, (int)Math.round(6.5), (int)Math.round(3.1), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Ряженка 1%", 40, "100г", uid, (int)Math.round(4.2), (int)Math.round(3), (int)Math.round(1)));
        appRepository.insertFood(new FoodEntity(0, "", "Морошка", 40, "100г", uid, (int)Math.round(7.4), (int)Math.round(0.8), (int)Math.round(0.9)));
        appRepository.insertFood(new FoodEntity(0, "", "Простокваша 1%", 40, "100г", uid, (int)Math.round(4.1), (int)Math.round(3), (int)Math.round(1)));
        appRepository.insertFood(new FoodEntity(0, "", "Кефир 1%", 40, "100г", uid, (int)Math.round(4), (int)Math.round(3), (int)Math.round(1)));
        appRepository.insertFood(new FoodEntity(0, "", "Укроп (зелень)", 40, "100г", uid, (int)Math.round(6.3), (int)Math.round(2.5), (int)Math.round(0.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Земляника", 41, "100г", uid, (int)Math.round(7.5), (int)Math.round(0.8), (int)Math.round(0.4)));
        appRepository.insertFood(new FoodEntity(0, "", "Лук репчатый", 41, "100г", uid, (int)Math.round(8.2), (int)Math.round(1.4), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Пахта", 41, "100г", uid, (int)Math.round(4.7), (int)Math.round(3.3), (int)Math.round(1)));
        appRepository.insertFood(new FoodEntity(0, "", "Кумыс нежирный (из коровьего молока)", 41, "100г", uid, (int)Math.round(6.3), (int)Math.round(3), (int)Math.round(0.05)));
        appRepository.insertFood(new FoodEntity(0, "", "Смородина белая", 42, "100г", uid, (int)Math.round(8), (int)Math.round(0.5), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Свекла", 42, "100г", uid, (int)Math.round(8.8), (int)Math.round(1.5), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Апельсин", 43, "100г", uid, (int)Math.round(8.1), (int)Math.round(0.9), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Смородина красная", 43, "100г", uid, (int)Math.round(7.7), (int)Math.round(0.6), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Папайя", 43, "100г", uid, (int)Math.round(10.8), (int)Math.round(0.5), (int)Math.round(0.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Абрикос", 44, "100г", uid, (int)Math.round(9), (int)Math.round(0.9), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Смородина чёрная", 44, "100г", uid, (int)Math.round(7.3), (int)Math.round(1), (int)Math.round(0.4)));
        appRepository.insertFood(new FoodEntity(0, "", "Черника", 44, "100г", uid, (int)Math.round(7.6), (int)Math.round(1.1), (int)Math.round(0.6)));
        appRepository.insertFood(new FoodEntity(0, "", "Нектарин", 44, "100г", uid, (int)Math.round(10.5), (int)Math.round(1.1), (int)Math.round(0.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Капуста кольраби", 44, "100г", uid, (int)Math.round(7.9), (int)Math.round(2.8), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Персик", 45, "100г", uid, (int)Math.round(9.5), (int)Math.round(0.9), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Крыжовник", 45, "100г", uid, (int)Math.round(9.1), (int)Math.round(0.7), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Листья одуванчика (зелень)", 45, "100г", uid, (int)Math.round(9.2), (int)Math.round(2.7), (int)Math.round(0.7)));
        appRepository.insertFood(new FoodEntity(0, "", "Сок апельсиновый", 45, "100г", uid, (int)Math.round(10.4), (int)Math.round(0.7), (int)Math.round(0.2)));
        appRepository.insertFood(new FoodEntity(0, "", "Молоко 1,5%", 45, "100г", uid, (int)Math.round(4.8), (int)Math.round(3), (int)Math.round(1.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Сок мандариновый", 45, "100г", uid, (int)Math.round(9.8), (int)Math.round(0.8), (int)Math.round(0)));
        appRepository.insertFood(new FoodEntity(0, "", "Малина", 46, "100г", uid, (int)Math.round(8.3), (int)Math.round(0.8), (int)Math.round(0.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Брусника", 46, "100г", uid, (int)Math.round(8.2), (int)Math.round(0.7), (int)Math.round(0.5)));
        appRepository.insertFood(new FoodEntity(0, "", "Сок яблочный", 46, "100г", uid, (int)Math.round(10.1), (int)Math.round(0.5), (int)Math.round(0.1)));
        appRepository.insertFood(new FoodEntity(0, "", "Груша", 47, "100г", uid, (int)Math.round(10.3), (int)Math.round(0.4), (int)Math.round(0.3)));
        appRepository.insertFood(new FoodEntity(0, "", "Яблоки", 47, "100г", uid, (int)Math.round(9.8), (int)Math.round(0.4), (int)Math.round(0.4)));
        appRepository.insertFood(new FoodEntity(0, "", "Киви", 47, "100г", uid, (int)Math.round(8.1), (int)Math.round(0.8), (int)Math.round(0.4)));





    }
}
